/**
 * FIELD-102 — Preview-only replay diagnostics (no route fixes).
 * Injected only via prepareInteractiveHtmlForPreview() in app.js.
 */
(function (global) {
  'use strict';

  const DIAG_BOOT = [
    '(function(){',
    '"use strict";',
    'if(window.__PLANAI_PREVIEW_DIAG__)return;',
    'window.__PLANAI_PREVIEW_DIAG__=true;',
    'var R=window.__PLANAI_REPORT__;',
    'var events=[];',
    'function ts(){return Date.now();}',
    'function log(tag,detail){',
    'events.push({t:ts(),tag:tag,detail:detail||""});',
    'if(events.length>120)events.shift();',
    '}',
    'function el(id){return document.getElementById(id);}',
    'function safe(fn,fallback){try{return fn();}catch(e){return fallback;}}',
    'function isIOS(){',
    'var ua=navigator.userAgent||"";',
    'return /iPad|iPhone|iPod/.test(ua)||(navigator.platform==="MacIntel"&&(navigator.maxTouchPoints||0)>1);',
    '}',
    'function normLon(p){return p&&(p.lon!=null?p.lon:p.lng);}',
    'function trackFeat(){',
    'if(!R)return null;',
    'var track=null;',
    'if(R.track&&R.track.path&&R.track.path.length>=2)track=R.track;',
    'if(!track){var evs=R.events||[];for(var i=0;i<evs.length;i++){if(evs[i]&&evs[i].kind==="track"&&evs[i].path&&evs[i].path.length>=2){track=evs[i];break;}}}',
    'return track;',
    '}',
    'function findMap(){',
    'if(window.__PLANAI_REPLAY_MAP__&&typeof window.__PLANAI_REPLAY_MAP__.project==="function")return window.__PLANAI_REPLAY_MAP__;',
    'var mapEl=document.querySelector(".maplibregl-map");',
    'if(mapEl&&mapEl._map)return mapEl._map;',
    'return null;',
    '}',
    'function parseSvgPoints(s){',
    'if(!s)return[];',
    'return s.trim().split(/\\s+/).filter(Boolean).map(function(pair){var xy=pair.split(",");return{x:+xy[0],y:+xy[1]};});',
    '}',
    'function safeArea(){',
    'var d=document.createElement("div");',
    'd.style.cssText="position:fixed;left:0;top:0;padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);visibility:hidden;";',
    'document.body.appendChild(d);',
    'var st=window.getComputedStyle(d);',
    'var out={top:st.paddingTop,right:st.paddingRight,bottom:st.paddingBottom,left:st.paddingLeft};',
    'd.remove();',
    'return out;',
    '}',
    'function parentPreview(){',
    'var out={modalVisible:"?",iframeLoaded:"?",iframeW:"?",iframeH:"?",previewW:"?",previewH:"?",srcdoc:location.href.indexOf("about:srcdoc")>=0||!location.href};',
    'try{',
    'var p=window.parent;if(!p||p===window)return out;',
    'var modal=p.document.getElementById("field-report-viewer");',
    'var frame=p.document.getElementById("field-report-viewer-frame");',
    'out.modalVisible=!!(modal&&modal.classList.contains("open"));',
    'out.iframeLoaded=!!(frame&&frame.contentWindow===window);',
    'if(frame){var fr=frame.getBoundingClientRect();out.iframeW=Math.round(fr.width)+"x"+Math.round(fr.height);}',
    'if(modal){var mr=modal.getBoundingClientRect();out.previewW=Math.round(mr.width)+"x"+Math.round(mr.height);}',
    '}catch(e){out.parentError=String(e&&e.message?e.message:e);}',
    'return out;',
    '}',
    'function buildSnapshot(){',
    'var map=findMap();',
    'var track=trackFeat();',
    'var wrap=document.getElementById("planai-route-svg-wrap");',
    'var line=wrap&&(wrap._line||wrap.querySelector("polyline:last-of-type"));',
    'var svgPts=line?parseSvgPoints(line.getAttribute("points")||""):[];',
    'var canvas=map?map.getCanvas():null;',
    'var container=map?map.getContainer():null;',
    'var cbox=container?container.getBoundingClientRect():null;',
    'var wbox=wrap?wrap.getBoundingClientRect():null;',
    'var vv=window.visualViewport;',
    'var proj=null;',
    'if(map&&track&&track.path&&track.path.length){',
    'var p0=track.path[0];',
    'var ll=[normLon(p0),p0.lat];',
    'var pr=safe(function(){return map.project(ll);},null);',
    'proj={lon:ll[0],lat:ll[1],x:pr?pr.x:null,y:pr?pr.y:null};',
    'if(pr&&(!Number.isFinite(pr.x)||!Number.isFinite(pr.y)))proj.bad="NaN";',
    'if(pr&&cbox&&(pr.x<0||pr.y<0||pr.x>cbox.width||pr.y>cbox.height))proj.offscreen=true;',
    '}',
    'var routeSrc=map?map.getSource("route"):null;',
    'var routeLine=map&&map.getLayer?map.getLayer("route-line"):null;',
    'var safariLine=map&&map.getLayer?map.getLayer("planai-route-safari-line"):null;',
    'return {',
    'preview:parentPreview(),',
    'ua:isIOS()?"iOS WebKit":"other",',
    'location:location.href||"(empty)",',
    'map:{',
    'found:!!map,',
    'loaded:map?!!map.loaded():false,',
    'styleLoaded:map?!!map.isStyleLoaded():false,',
    'canvas:canvas?canvas.width+"x"+canvas.height:"n/a",',
    'zoom:map?map.getZoom():null,',
    'center:map?map.getCenter():null,',
    'pitch:map?map.getPitch():null,',
    'bearing:map?map.getBearing():null',
    '},',
    'route:{',
    'trackExists:!!track,',
    'pointCount:track?track.path.length:0,',
    'first:track&&track.path[0]?{lat:track.path[0].lat,lon:normLon(track.path[0])}:null,',
    'last:track&&track.path.length?{lat:track.path[track.path.length-1].lat,lon:normLon(track.path[track.path.length-1])}:null,',
    'sourceRoute:!!routeSrc,',
    'layerRouteLine:!!routeLine,',
    'layerSafariLine:!!safariLine,',
    'svgExists:!!wrap,',
    'svgPoints:svgPts.length,',
    'svgBox:wbox?Math.round(wbox.width)+"x"+Math.round(wbox.height):"n/a",',
    'svgZ:wrap?window.getComputedStyle(wrap).zIndex:"n/a",',
    'svgParent:wrap&&wrap.parentElement?wrap.parentElement.className:"n/a",',
    'needsSvgFallback:isIOS()',
    '},',
    'projection:proj,',
    'layout:{',
    'containerBox:cbox?{w:Math.round(cbox.width),h:Math.round(cbox.height),l:Math.round(cbox.left),t:Math.round(cbox.top)}:null,',
    'visualViewport:vv?{w:Math.round(vv.width),h:Math.round(vv.height),scale:vv.scale,offsetTop:vv.offsetTop,offsetLeft:vv.offsetLeft}:null,',
    'dpr:window.devicePixelRatio,',
    'orientation:screen.orientation?screen.orientation.type:(window.innerWidth>window.innerHeight?"landscape":"portrait"),',
    'safeArea:safeArea()',
    '},',
    'events:events.slice(-18)',
    '};',
    '}',
    'function fmtObj(o,indent){',
    'indent=indent||0;',
    'var pad=new Array(indent+1).join(" ");',
    'if(o===null||o===undefined)return String(o);',
    'if(typeof o!=="object")return String(o);',
    'if(Array.isArray(o))return o.map(function(x){return fmtObj(x,indent);}).join("\\n"+pad);',
    'return Object.keys(o).map(function(k){',
    'var v=o[k];',
    'if(v&&typeof v==="object"&&!Array.isArray(v)){return pad+k+":\\n"+fmtObj(v,indent+2);}',
    'return pad+k+": "+fmtObj(v,indent);',
    '}).join("\\n");',
    '}',
    'function render(){',
    'var snap=buildSnapshot();',
    'var host=el("planai-preview-diag-panel");',
    'if(!host)return;',
    'host.textContent=',
    '"FIELD-102 Preview Diagnostics\\n"+',
    '"Updated: "+new Date().toISOString()+"\\n\\n"+',
    '"=== PREVIEW ===\\n"+fmtObj(snap.preview,0)+"\\n\\n"+',
    '"=== MAPLIBRE ===\\n"+fmtObj(snap.map,0)+"\\n\\n"+',
    '"=== ROUTE ===\\n"+fmtObj(snap.route,0)+"\\n\\n"+',
    '"=== PROJECTION (pt 0) ===\\n"+fmtObj(snap.projection,0)+"\\n\\n"+',
    '"=== LAYOUT ===\\n"+fmtObj(snap.layout,0)+"\\n\\n"+',
    '"=== META ===\\nua: "+snap.ua+"\\nloc: "+snap.location+"\\n\\n"+',
    '"=== EVENTS ===\\n"+snap.events.map(function(e){return new Date(e.t).toISOString().slice(11,23)+" "+e.tag+(e.detail?" "+e.detail:"");}).join("\\n");',
    '}',
    'function mount(){',
    'if(el("planai-preview-diag-panel"))return;',
    'var panel=document.createElement("pre");',
    'panel.id="planai-preview-diag-panel";',
    'panel.setAttribute("data-planai-diag","1");',
    'panel.style.cssText="position:fixed;left:8px;top:8px;right:8px;max-width:calc(100vw - 16px);max-height:46vh;overflow:auto;margin:0;padding:10px 12px;font:11px/1.35 ui-monospace,Menlo,Consolas,monospace;color:#e8f4ff;background:rgba(8,16,28,0.92);border:1px solid #3d5a80;border-radius:10px;z-index:2147483647;pointer-events:auto;white-space:pre-wrap;word-break:break-word;-webkit-overflow-scrolling:touch;box-shadow:0 8px 32px rgba(0,0,0,0.45);";',
    'document.body.appendChild(panel);',
    'var btn=document.createElement("button");',
    'btn.textContent="×";',
    'btn.style.cssText="position:fixed;top:10px;right:12px;z-index:2147483647;width:32px;height:32px;border-radius:8px;border:1px solid #3d5a80;background:#1a2a40;color:#fff;font-size:18px;";',
    'btn.onclick=function(){panel.style.display=panel.style.display==="none"?"block":"none";};',
    'document.body.appendChild(btn);',
    '}',
    'function hookMap(map){',
    'if(!map||map.__planaiDiagHooked)return;',
    'map.__planaiDiagHooked=true;',
    'log("map.hooked");',
    '["load","style.load","render","idle","resize"].forEach(function(ev){',
    'map.on(ev,function(){log("map."+ev);});',
    '});',
    'map.on("load",function(){log("route.drawn?", "native layers at load");});',
    '}',
    'function watch(){',
    'var map=findMap();',
    'if(map)hookMap(map);',
    'var wrap=document.getElementById("planai-route-svg-wrap");',
    'if(wrap&&!wrap.__planaiDiagHooked){',
    'wrap.__planaiDiagHooked=true;',
    'log("svg.found");',
    'if(typeof wrap._redraw==="function"){',
    'var orig=wrap._redraw;',
    'wrap._redraw=function(){log("svg.redraw");return orig.apply(this,arguments);};',
    '}',
    '}',
    'render();',
    '}',
    'log("diag.boot", "preview iframe");',
    'window.addEventListener("load",function(){log("window.load");});',
    'window.addEventListener("orientationchange",function(){log("orientationchange");});',
    'if(window.visualViewport){',
    'window.visualViewport.addEventListener("resize",function(){log("visualViewport.resize");});',
    '}',
    'document.addEventListener("DOMContentLoaded",function(){log("DOMContentLoaded");});',
    'setTimeout(function(){log("replay.started","t+2s");},2000);',
    'mount();',
    'watch();',
    'setInterval(watch,500);',
    '})();',
  ].join('');

  function isPreviewDiagnosticMode() {
    try {
      if (global.__PLANAI_PREVIEW_DIAG_MODE__) return true;
      if (/[?&]previewDiag=1(?:&|$)/.test(global.location?.search || '')) return true;
      if (global.localStorage?.getItem('PLANAI_PREVIEW_DIAG') === '1') return true;
    } catch (_) { /* ignore */ }
    const ua = global.navigator?.userAgent || '';
    const iOS = /iPad|iPhone|iPod/.test(ua);
    const iPadOS = global.navigator?.platform === 'MacIntel' && (global.navigator?.maxTouchPoints || 0) > 1;
    return iOS || iPadOS;
  }

  function injectPreviewDiagnostics(html) {
    if (!html || typeof html !== 'string') return html;
    if (!html.includes('id="root"') || !html.includes('window.__PLANAI_REPORT__')) return html;
    if (html.includes('id="planai-preview-diagnostics"')) return html;
    const script = '<script id="planai-preview-diagnostics">' + DIAG_BOOT + '<\/script>';
    if (html.includes('</body>')) return html.replace('</body>', script + '</body>');
    return html + script;
  }

  global.FieldReplayPreviewDiagnostics = {
    isPreviewDiagnosticMode,
    injectPreviewDiagnostics,
    DIAG_BOOT,
  };
})(typeof window !== 'undefined' ? window : globalThis);
