/**
 * Cinematic replay HTML fixes — MapLibre overlays above satellite + centered playback controls.
 * deck.gl interleaved layers can render under embedded raster basemaps on some GPUs / https demo.
 */
(function (global) {
  'use strict';

  const MAP_OVERLAY_BOOT = [
    '(function(){',
    '"use strict";',
    'var R=window.__PLANAI_REPORT__;',
    'if(!R)return;',
    'function start(){',
    'var HOOKED=new WeakSet();',
    'var ROUTE_LAYER_IDS=["planai-route-safari-glow","planai-route-safari-line","planai-route-safari-dots"];',
    'function isIOSWebKit(){',
    'var ua=navigator.userAgent||"";',
    'var touchMac=navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1;',
    'return /iPad|iPhone|iPod/.test(ua)||touchMac;',
    '}',
    'function needsSvgRouteFallback(){',
    'if(isIOSWebKit())return true;',
    'try{',
    'if(window.self!==window.top)return true;',
    'var p=(location.protocol||"").toLowerCase();',
    'if(p==="about:"||p==="blob:")return true;',
    '}catch(e){}',
    'return false;',
    '}',
    'function densifyCoords(c,step){',
    'if(!c||c.length<2)return c||[];',
    'step=step||0.000055;',
    'var out=[c[0]];',
    'for(var i=1;i<c.length;i++){',
    'var a=c[i-1],b=c[i],dx=b[0]-a[0],dy=b[1]-a[1],dist=Math.sqrt(dx*dx+dy*dy),n=Math.max(1,Math.ceil(dist/step));',
    'for(var j=1;j<=n;j++){var t=j/n;out.push([a[0]+dx*t,a[1]+dy*t]);}',
    '}',
    'return out;',
    '}',
    'function normLon(p){return p&&(p.lon!=null?p.lon:p.lng);}',
    'function normPath(path){',
    'return(path||[]).map(function(p){return{lat:p.lat,lon:normLon(p),ts:p.ts||""};})',
    '.filter(function(p){return Number.isFinite(p.lat)&&Number.isFinite(p.lon);});',
    '}',
    'if(R.track&&R.track.path)R.track.path=normPath(R.track.path);',
    '(R.events||[]).forEach(function(e){if(e&&e.kind==="track"&&e.path)e.path=normPath(e.path);});',
    'function trackFromProject(){',
    'var objs=(R.project&&R.project.objects)||[];',
    'for(var i=0;i<objs.length;i++){',
    'var o=objs[i];',
    'if(o&&o.type==="field_gps_track"&&o.vertices&&o.vertices.length>=2){',
    'return{kind:"track",path:normPath(o.vertices)};',
    '}',
    '}',
    'return null;',
    '}',
    'function synthPathFromTimeline(){',
    'var pts=[];',
    '(R.events||[]).forEach(function(e){',
    'if(!e||e.kind==="track"||e.kind==="start"||e.kind==="end")return;',
    'var lon=normLon(e);',
    'if(Number.isFinite(e.lat)&&Number.isFinite(lon))pts.push({lat:e.lat,lon:lon,ts:e.ts||""});',
    '});',
    'if(pts.length<2)return null;',
    'return{kind:"track",path:pts};',
    '}',
    'function trackFeat(){',
    'var track=null;',
    'if(R.track&&R.track.path&&R.track.path.length>=2)track=R.track;',
    'if(!track){',
    'var evs=R.events||[];',
    'for(var i=0;i<evs.length;i++){',
    'if(evs[i]&&evs[i].kind==="track"&&evs[i].path&&evs[i].path.length>=2){track=evs[i];break;}',
    '}',
    '}',
    'if(!track||!track.path||track.path.length<2)track=trackFromProject();',
    'if(!track||!track.path||track.path.length<2)track=synthPathFromTimeline();',
    'return track;',
    '}',
    'function eventFeatures(){',
    'var feats=[];',
    '(R.events||[]).forEach(function(e){',
    'if(!e||(e.kind!=="photo"&&e.kind!=="note"&&e.kind!=="audio"))return;',
    'var lon=normLon(e);',
    'if(!Number.isFinite(e.lat)||!Number.isFinite(lon))return;',
    'feats.push({type:"Feature",properties:{kind:e.kind,label:e.label||""},geometry:{type:"Point",coordinates:[lon,e.lat]}});',
    '});',
    'return{type:"FeatureCollection",features:feats};',
    '}',
    'function findMap(){',
    'function ok(m){return m&&typeof m.project==="function"&&typeof m.getContainer==="function";}',
    'if(window.__PLANAI_REPLAY_MAP__&&ok(window.__PLANAI_REPLAY_MAP__))return window.__PLANAI_REPLAY_MAP__;',
    'var nodes=document.querySelectorAll(".maplibregl-ctrl,.maplibregl-ctrl-group,.mapboxgl-ctrl,.mapboxgl-ctrl-group");',
    'for(var i=0;i<nodes.length;i++){if(ok(nodes[i]._map))return nodes[i]._map;}',
    'var mapEl=document.querySelector(".maplibregl-map,.mapboxgl-map");',
    'if(mapEl){',
    'if(ok(mapEl._map))return mapEl._map;',
    'var names=Object.getOwnPropertyNames(mapEl);',
    'for(var j=0;j<names.length;j++){if(ok(mapEl[names[j]]))return mapEl[names[j]];}',
    'for(var k in mapEl){if(!Object.prototype.hasOwnProperty.call(mapEl,k))continue;var v=mapEl[k];if(ok(v))return v;}',
    'var all=mapEl.getElementsByTagName("*");',
    'for(var n=0;n<all.length;n++){if(ok(all[n]._map))return all[n]._map;}',
    '}',
    'try{',
    'function _walk(start){',
    'if(!start)return null;',
    'var seen=new Set(),stack=[start],steps=0;',
    'while(stack.length&&steps<300000){steps++;var f=stack.pop();',
    'if(!f||typeof f!=="object"||seen.has(f))continue;seen.add(f);',
    'var ms=f.memoizedState,hops=0;',
    'while(ms&&hops<150){hops++;var v=ms.memoizedState;',
    'if(v&&typeof v==="object"){if(ok(v))return v;if(ok(v.current))return v.current;}',
    'ms=ms.next;}',
    'if(f.child)stack.push(f.child);',
    'if(f.sibling)stack.push(f.sibling);}',
    'return null;',
    '}',
    'var hosts=[document.getElementById("root")];',
    'var mEl2=document.querySelector(".maplibregl-map,.mapboxgl-map");if(mEl2)hosts.push(mEl2);',
    'for(var hi=0;hi<hosts.length;hi++){var rel=hosts[hi];if(!rel)continue;',
    'var keys=Object.keys(rel);',
    'for(var ki=0;ki<keys.length;ki++){var kk=keys[ki];',
    'if(kk.indexOf("__reactContainer$")!==0&&kk.indexOf("__reactFiber$")!==0&&kk.indexOf("__reactInternalInstance$")!==0)continue;',
    'var fib=rel[kk];var starts=[];',
    'if(fib){if(fib.stateNode&&fib.stateNode.current)starts.push(fib.stateNode.current);starts.push(fib);if(fib.child)starts.push(fib.child);}',
    'for(var si=0;si<starts.length;si++){var mm=_walk(starts[si]);if(mm)return mm;}',
    '}}',
    '}catch(e){}',
    'return null;',
    '}',
    'function clearLineLayers(map){',
    '["planai-route-safari-glow","planai-route-safari-line"].forEach(function(id){try{if(map.getLayer(id))map.removeLayer(id);}catch(e){}});',
    'try{if(map.getSource("planai-route-safari"))map.removeSource("planai-route-safari");}catch(e){}',
    '}',
    'function clearRouteLayers(map){',
    'ROUTE_LAYER_IDS.forEach(function(id){try{if(map.getLayer(id))map.removeLayer(id);}catch(e){}});',
    'try{if(map.getSource("planai-route-safari"))map.removeSource("planai-route-safari");}catch(e){}',
    'try{if(map.getSource("planai-route-dots"))map.removeSource("planai-route-dots");}catch(e){}',
    '}',
    'function raiseOverlay(map){',
    '["route-progress-line","route-line","route-glow","planai-events-halo","planai-events-points","planai-events-labels","planai-route-safari-glow","planai-route-safari-line","planai-route-safari-dots"].forEach(function(id){',
    'try{if(map.getLayer(id))map.moveLayer(id);}catch(e){}',
    '});',
    '}',
    'function ensureSvgRoute(map){',
    'var track=trackFeat();',
    'if(!track)return;',
    'var lngLat=track.path.map(function(p){return[p.lon,p.lat];});',
    'if(lngLat.length<2)return;',
    'var host=map.getContainer();',
    'if(!host)return;',
    'var mount=host.parentElement||host;',
    'var wrap=mount.querySelector("#planai-route-svg-wrap")||host.querySelector("#planai-route-svg-wrap");',
    'var SVG_NS="http://www.w3.org/2000/svg";',
    'if(!wrap){',
    'wrap=document.createElement("div");',
    'wrap.id="planai-route-svg-wrap";',
    'wrap.style.cssText="position:absolute;inset:0;pointer-events:none;z-index:12;overflow:hidden;";',
    'var svg=document.createElementNS(SVG_NS,"svg");',
    'svg.setAttribute("width","100%");svg.setAttribute("height","100%");',
    'svg.style.cssText="display:block;overflow:visible;";',
    'var glow=document.createElementNS(SVG_NS,"polyline");',
    'glow.setAttribute("fill","none");glow.setAttribute("stroke","#ffffff");',
    'glow.setAttribute("stroke-width","12");glow.setAttribute("stroke-opacity","0.7");',
    'glow.setAttribute("stroke-linecap","round");glow.setAttribute("stroke-linejoin","round");',
    'var line=document.createElementNS(SVG_NS,"polyline");',
    'line.setAttribute("fill","none");line.setAttribute("stroke","#27ae60");',
    'line.setAttribute("stroke-width","6");line.setAttribute("stroke-linecap","round");line.setAttribute("stroke-linejoin","round");',
    'svg.appendChild(glow);svg.appendChild(line);wrap.appendChild(svg);',
    'try{mount.appendChild(wrap);}catch(e){host.appendChild(wrap);}',
    'wrap._glow=glow;wrap._line=line;',
    'var redraw=function(){',
    'try{',
    'var pts=(wrap._lngLat||[]).map(function(ll){return map.project(ll);});',
    'var s=pts.map(function(p){return p.x+","+p.y;}).join(" ");',
    'wrap._glow.setAttribute("points",s);wrap._line.setAttribute("points",s);',
    '}catch(e){}',
    '};',
    'wrap._redraw=redraw;',
    'if(!wrap._hooked){wrap._hooked=true;',
    '["move","zoom","rotate","pitch","resize","idle"].forEach(function(ev){map.on(ev,redraw);});',
    '}',
    '}',
    'wrap._lngLat=lngLat;',
    'wrap._redraw();',
    '}',
    'function ensureRoute(map){',
    'var track=trackFeat();',
    'if(!track)return;',
    'var c=track.path.map(function(p){return[p.lon,p.lat];});',
    'if(c.length<2)return;',
    'var ios=needsSvgRouteFallback();',
    'if(ios){',
    'clearLineLayers(map);',
    'try{if(map.getLayer("planai-route-safari-dots"))map.removeLayer("planai-route-safari-dots");}catch(e){}',
    'try{if(map.getSource("planai-route-dots"))map.removeSource("planai-route-dots");}catch(e){}',
    'ensureSvgRoute(map);',
    'return;',
    '}',
    'var feat={type:"Feature",properties:{},geometry:{type:"LineString",coordinates:c}};',
    'var trailCoords=c;',
    'var dotFeats=trailCoords.map(function(pt){return{type:"Feature",properties:{},geometry:{type:"Point",coordinates:pt}};});',
    'var dotData={type:"FeatureCollection",features:dotFeats};',
    'try{',
    'var src=map.getSource("planai-route-safari");',
    'if(!src||!map.getLayer("planai-route-safari-line")){',
    'clearLineLayers(map);',
    'map.addSource("planai-route-safari",{type:"geojson",data:feat});',
    'map.addLayer({id:"planai-route-safari-glow",type:"line",source:"planai-route-safari",',
    'layout:{"line-cap":"round","line-join":"round"},',
    'paint:{"line-color":"#ffffff","line-width":12,"line-opacity":0.75}});',
    'map.addLayer({id:"planai-route-safari-line",type:"line",source:"planai-route-safari",',
    'layout:{"line-cap":"round","line-join":"round"},',
    'paint:{"line-color":"#27ae60","line-width":6,"line-opacity":1}});',
    '}else{src.setData(feat);}',
    'var dotRadius=3;',
    'var dotSrc=map.getSource("planai-route-dots");',
    'if(!dotSrc||!map.getLayer("planai-route-safari-dots")){',
    'if(dotSrc)try{map.removeSource("planai-route-dots");}catch(e){}',
    'if(map.getLayer("planai-route-safari-dots"))try{map.removeLayer("planai-route-safari-dots");}catch(e){}',
    'map.addSource("planai-route-dots",{type:"geojson",data:dotData});',
    'map.addLayer({id:"planai-route-safari-dots",type:"circle",source:"planai-route-dots",',
    'paint:{"circle-radius":dotRadius,"circle-color":"#27ae60","circle-opacity":0.9,',
    '"circle-stroke-width":1,"circle-stroke-color":"#ffffff","circle-pitch-alignment":"map"}});',
    '}else{dotSrc.setData(dotData);try{map.setPaintProperty("planai-route-safari-dots","circle-radius",dotRadius);}catch(e){}}',
    '}catch(e){}',
    '}',
    'function ensureEvents(map){',
    'var data=eventFeatures();',
    'if(!data.features.length)return;',
    'try{',
    'var src=map.getSource("planai-events");',
    'if(src){src.setData(data);}',
    'else{map.addSource("planai-events",{type:"geojson",data:data});}',
    'if(!map.getLayer("planai-events-halo")){',
    'map.addLayer({id:"planai-events-halo",type:"circle",source:"planai-events",',
    'paint:{"circle-radius":16,"circle-color":"#ffffff","circle-opacity":0.45}});',
    '}',
    'if(!map.getLayer("planai-events-points")){',
    'map.addLayer({id:"planai-events-points",type:"circle",source:"planai-events",',
    'paint:{"circle-radius":11,',
    '"circle-color":["match",["get","kind"],"photo","#d4a853","#a78bfa"],',
    '"circle-stroke-width":3,"circle-stroke-color":"#ffffff","circle-opacity":1}});',
    '}',
    'if(!map.getLayer("planai-events-labels")){',
    'map.addLayer({id:"planai-events-labels",type:"symbol",source:"planai-events",',
    'layout:{"text-field":["get","label"],"text-size":11,"text-offset":[0,-1.8],"text-anchor":"top","text-allow-overlap":true,"text-optional":true},',
    'paint:{"text-color":"#ffffff","text-halo-color":"#0f1a28","text-halo-width":1.5}});',
    '}',
    '}catch(e){}',
    '}',
    'function ensureOverlay(map){',
    'if(!map)return;',
    'if(needsSvgRouteFallback()){ensureSvgRoute(map);raiseOverlay(map);return;}',
    'if(typeof map.isStyleLoaded==="function"&&!map.isStyleLoaded()){',
    'map.once("load",function(){ensureOverlay(map);});',
    'return;',
    '}',
    'ensureRoute(map);',
    'ensureEvents(map);',
    'raiseOverlay(map);',
    '}',
    'function hookMap(map){',
    'if(!map||HOOKED.has(map))return;',
    'HOOKED.add(map);',
    'var run=function(){ensureOverlay(map);};',
    'if(typeof map.isStyleLoaded==="function"&&map.isStyleLoaded())run();',
    'map.once("load",run);',
    'map.once("idle",run);',
    'if(needsSvgRouteFallback()){map.on("idle",function(){ensureSvgRoute(map);raiseOverlay(map);});}',
    '}',
    'function tick(){',
    'var map=findMap();',
    'if(map){window.__PLANAI_REPLAY_MAP__=map;hookMap(map);if(needsSvgRouteFallback()){ensureSvgRoute(map);raiseOverlay(map);}}',
    '}',
    'var tries=0;var iv=setInterval(function(){tick();tries++;if(tries>180)clearInterval(iv);},400);',
    '}',
    'function defer(){setTimeout(start,1600);}',
    'if(document.readyState==="complete")defer();',
    'else window.addEventListener("load",defer);',
    '})();',
  ].join('');

  const CONTROLS_BOOT = [
    '(function(){',
    '"use strict";',
    'function centerBar(el){',
    'if(!el)return;',
    'var w="min(560px, calc(100vw - 2rem))";',
    'el.setAttribute("data-planai-centered","1");',
    'el.setAttribute("data-planai-playback-dock","1");',
    'el.style.setProperty("position","fixed","important");',
    'el.style.setProperty("left","50%","important");',
    'el.style.setProperty("right","auto","important");',
    'el.style.setProperty("transform","translateX(-50%)","important");',
    'el.style.setProperty("margin-left","0","important");',
    'el.style.setProperty("margin-right","0","important");',
    'el.style.setProperty("width",w,"important");',
    'el.style.setProperty("max-width",w,"important");',
    '}',
    'function center(){',
    'var root=document.getElementById("root");',
    'if(!root||!root.childElementCount)return;',
    'var seen=new Set();',
    'function tryCenter(el){if(!el||seen.has(el))return;seen.add(el);centerBar(el);}',
    'root.querySelectorAll("input[type=range]").forEach(function(inp){',
    'var el=inp.parentElement;',
    'while(el&&el!==document.body){',
    'var st=window.getComputedStyle(el);',
    'var bottom=parseFloat(st.bottom||"");',
    'if((st.position==="fixed"||st.position==="absolute")&&bottom>=0&&bottom<220){tryCenter(el);break;}',
    'el=el.parentElement;',
    '}',
    '});',
    'root.querySelectorAll("*").forEach(function(el){',
    'if(el.querySelectorAll("button").length<3)return;',
    'var st=window.getComputedStyle(el);',
    'if(st.position!=="fixed"&&st.position!=="absolute")return;',
    'var b=parseFloat(st.bottom);',
    'if(!(b>=0&&b<220))return;',
    'var txt=(el.textContent||"").toLowerCase();',
    'if(txt.indexOf("duraklat")>=0||txt.indexOf("oynat")>=0||txt.indexOf("pause")>=0||txt.indexOf("play")>=0)tryCenter(el);',
    '});',
    '}',
    'function start(){center();var n=0;var iv=setInterval(function(){center();n++;if(n>60)clearInterval(iv);},500);}',
    'function defer(){setTimeout(start,1800);}',
    'if(document.readyState==="complete")defer();',
    'else window.addEventListener("load",defer);',
    '})();',
  ].join('');

  const REPLAY_UI_CSS = [
    '#planai-replay-ui-fix input[type=range]{width:100%;}',
    '#root [data-planai-centered],#root [data-planai-playback-dock]{',
    'left:50%!important;right:auto!important;',
    'transform:translateX(-50%)!important;margin-left:0!important;margin-right:0!important;',
    'width:min(560px, calc(100vw - 2rem))!important;max-width:min(560px, calc(100vw - 2rem))!important;}',
    '#root *:has(> input[type=range]){',
    'left:50%!important;right:auto!important;',
    'transform:translateX(-50%)!important;margin-left:0!important;}',
  ].join('');

  function stripHarmfulReplayPatches(html) {
    if (!html || typeof html !== 'string') return html;
    return html
      .replace(/<script id="planai-replay-gate">[\s\S]*?<\/script>/gi, '')
      .replace(/<script id="planai-replay-safe">[\s\S]*?<\/script>/gi, '')
      .replace(/<script id="planai-replay-watchdog">[\s\S]*?<\/script>/gi, '')
      .replace(/<style id="planai-psr-fallback">[\s\S]*?<\/style>/gi, '')
      .replace(/<div id="psr-app"[^>]*>\s*<\/div>/gi, '');
  }

  function stripReplayPatches(html) {
    if (!html || typeof html !== 'string') return html;
    return stripHarmfulReplayPatches(html)
      .replace(/<script id="planai-safari-route-fix">[\s\S]*?<\/script>/gi, '')
      .replace(/<script id="planai-replay-controls-fix">[\s\S]*?<\/script>/gi, '')
      .replace(/<style id="planai-replay-ui-fix">[\s\S]*?<\/style>/gi, '');
  }

  function injectRouteFix(html) {
    if (!html || typeof html !== 'string') return html;
    if (!html.includes('id="root"') || !html.includes('window.__PLANAI_REPORT__')) return html;
    html = stripReplayPatches(html);
    const uiStyle = '<style id="planai-replay-ui-fix">' + REPLAY_UI_CSS + '</style>';
    const routeScript = '<script id="planai-safari-route-fix">' + MAP_OVERLAY_BOOT + '</script>';
    const controlsScript = '<script id="planai-replay-controls-fix">' + CONTROLS_BOOT + '</script>';
    if (html.includes('</body>')) {
      return html.replace('</body>', uiStyle + routeScript + controlsScript + '</body>');
    }
    return html + uiStyle + routeScript + controlsScript;
  }

  /** @deprecated use injectRouteFix */
  function inject(html) {
    return injectRouteFix(html);
  }

  global.FieldReplaySafariRoute = {
    inject,
    injectRouteFix,
    stripReplayPatches,
    stripHarmfulReplayPatches,
    MAP_OVERLAY_BOOT,
    CONTROLS_BOOT,
    ROUTE_BOOT: MAP_OVERLAY_BOOT,
  };
})(typeof window !== 'undefined' ? window : globalThis);
